language: python

# json requirements > 2.5 
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install:
  - pip install pylint pep8
# command to run tests
script:
  - pylint check_puppet_nodes.py
  - pep8 check_puppet_nodes.py
